program test_marlin_components;
{$mode objfpc}{$H+}
uses Classes, SysUtils, Math, aigcodeparser, aimarlinsimulator, aivirtualserialpair;
type
  TObserver = class
    Replies: string;
    MotionCount: Integer;
    Deposit: Double;
    procedure Reply(Sender: TObject; const Text: string);
    procedure Motion(Sender: TObject; const A,B: TAIMarlinPosition; Material: Double);
  end;
var S: TAIMarlinSimulator; O: TObserver; C: TAIGCodeCommand;
    Err,Line: string; Args: TStringList; Pair: TAIVirtualSerialPair; I: Integer;
procedure Check(B: Boolean; const Msg: string);
begin if not B then raise Exception.Create(Msg); end;
procedure Near(A,B: Double; const Msg: string);
begin Check(Abs(A-B)<1e-6, Msg+' actual='+FloatToStr(A)); end;
procedure TObserver.Reply(Sender: TObject; const Text: string);
begin Replies := Replies + Text; end;
procedure TObserver.Motion(Sender: TObject; const A,B: TAIMarlinPosition; Material: Double);
begin Inc(MotionCount); Deposit := Deposit + Material; end;
function Numbered(N: Integer; const Text: string): string;
begin
  Result := 'N'+IntToStr(N)+' '+Text;
  Result := Result+'*'+IntToStr(TAIGCodeParser.Checksum(Result));
end;
procedure Command(const Text: string; Seconds: Double = 0);
begin Check(S.SubmitLine(Text),'Submit '+Text); S.Advance(Seconds); end;
procedure NewSession;
begin S.Reset; O.Replies := ''; O.Deposit := 0; O.MotionCount := 0; end;
begin
  S := TAIMarlinSimulator.Create(nil); O := TObserver.Create;
  Pair := TAIVirtualSerialPair.Create(nil); Args := TStringList.Create;
  try
    S.OnResponse := @O.Reply; S.OnMotion := @O.Motion;
    DefaultFormatSettings.DecimalSeparator := ',';
    Check(TAIGCodeParser.Parse('G1X1.5Y-2E.25 (test); tail',C,Err),Err);
    Near(C.Values['X'],1.5,'Invariant decimal parser');
    Near(C.Values['E'],0.25,'Compact E');
    Check(not TAIGCodeParser.Parse('G1 X1,5',C,Err),'Reject decimal comma');
    Check(not TAIGCodeParser.Parse('G1 X1 X2',C,Err),'Reject duplicates');
    Check(not TAIGCodeParser.Parse('G1 Xnan',C,Err),'Reject invalid numeric value');
    Check(not TAIGCodeParser.Parse('G1 X1 (oops',C,Err),'Reject comment');
    Line := Numbered(1,'G1 X10');
    Check(TAIGCodeParser.Parse(Line,C,Err),'Checksum');
    Check(not TAIGCodeParser.Parse(Line+'0',C,Err),'Bad checksum');
    Writeln('PASS parser, comments, compact words, checksum, locale');

    NewSession;
    S.Receive('M11'); Check(O.Replies='','Fragment waits'); S.Receive('5'+#13#10);
    Check(Pos('FIRMWARE_NAME:Marlin-Simulator',O.Replies)>0,'Firmware response');
    Command('M302 P1'); O.Replies := '';
    Command('G1 X60 E6 F60',30);
    Near(S.State.Position.X,30,'Halfway motion'); Near(O.Deposit,3,'Half deposit');
    Check(Pos('ok',O.Replies)=0,'No premature completion');
    S.Pause; S.Advance(10); Near(S.State.Position.X,30,'Pause freezes motion');
    S.Resume; S.Advance(30); Near(S.State.Position.X,60,'Final motion');
    Near(O.Deposit,6,'Total material'); Check(S.IsIdle,'Finished');
    Command('G92 X0 E0'); Near(S.State.Position.X,60,'G92 is not motion');
    Command('G1 X10 E1 F600',1); Near(S.State.Position.X,70,'G92 offset');
    Command('M83'); Command('G1 E-2 F120',1); Near(S.State.RetractedFilament,2,'Retract');
    O.Deposit := 0; Command('G1 E2 F120',1); Near(O.Deposit,0,'Unretract is not deposition');
    Command('G91'); Command('G1 X1 F60',1); Near(S.State.Position.X,71,'Relative motion');
    Command('G90'); Check(not S.State.RelativeE,'G90 resets E mode');
    Command('M114'); Check(Pos('X:11.000',O.Replies)>0,'Logical position and decimal dot');
    Command('G28 X'); Near(S.State.Position.X,0,'Home axis');
    Writeln('PASS timed motion, pause, extrusion, offsets, retraction, homing');

    NewSession;
    Command('G1 X10 E1 F600',1); Near(S.State.Position.X,0,'Cold move rejected');
    Check(Pos('Cold extrusion',S.LastError)>0,'Cold error');
    Command('M109 S55',5); Near(S.State.Hotend,40,'Heating rate');
    Check(S.Pending=mpHotend,'Waiting');
    Command('M105'); Check(Pos('ok T:40.000 /55.000',O.Replies)>0,'Temperature during wait');
    S.Advance(5); Check(S.IsIdle,'Heating completes');
    Command('M109 S30'); Check(S.IsIdle,'S does not wait for cooling');
    Command('M109 R30',25); Near(S.State.Hotend,30,'R waits cooling'); Check(S.IsIdle,'Cooling complete');
    Command('M190 S33',10); Near(S.State.Bed,33,'Bed heating');
    Command('M109 S200'); Command('M108'); Check(S.IsIdle,'Cancel heat wait');
    Command('G4 P1000',0.5); Check(not S.IsIdle,'Dwell pending');
    S.Advance(0.5); Check(S.IsIdle,'Dwell complete');
    Writeln('PASS thermal wait S/R, M105, M108, bed and dwell');

    NewSession;
    Check(S.SubmitLine(Numbered(1,'G1 X10 F600')),'Line 1');
    Check(not S.SubmitLine(Numbered(3,'G1 X30')),'Skipped line rejected');
    Check(Pos('Resend:2',O.Replies)>0,'Resend expected');
    Check(not S.SubmitLine('N2 G1 X20'),'Checksum required');
    Check(S.SubmitLine(Numbered(2,'M400')),'Barrier queued');
    S.Advance(1); Check(S.IsIdle,'FIFO barrier');
    Check(S.SubmitLine(Numbered(99,'M110 N0')),'Reset sequence');
    Check(S.LastLineNumber=0,'Inner N for M110');
    Check(not S.SubmitLine('M110 N10 X1'),'Invalid M110 rejected');
    Check(S.LastLineNumber=0,'Invalid M110 leaves sequence intact');
    Check(S.SubmitLine(Numbered(1,'G1 X20 F600')),'Restart sequence');
    S.Advance(0.5); S.Receive('M112'+#10);
    Check(S.State.Killed and S.IsIdle,'Immediate kill clears work');
    S.Advance(10); Near(S.State.Position.X,15,'Killed motion stops');
    Check(not S.SubmitLine('G1 X1'),'Killed blocks commands');
    NewSession;
    for I := 1 to 128 do Check(S.SubmitLine(Numbered(I,'G4 P1')),'Queue fill');
    Check(not S.SubmitLine(Numbered(129,'G4 P1')),'Bounded queue');
    Check(S.LastLineNumber=128,'Rejected line not consumed');
    S.Advance(1); Check(S.IsIdle,'Drain queue');
    Check(S.SubmitLine(Numbered(129,'G4 P1')),'Resend after drain'); S.Advance(1);
    S.Receive(StringOfChar('X',1025)+#10+'M115'+#10);
    Check(Pos('Input line too long',O.Replies)>0,'Bounded RX');
    Check(Pos('FIRMWARE_NAME',O.Replies)>0,'RX recovers');
    Command('G2 X20'); Check(Pos('Unsupported G2',S.LastError)>0,'No fake arc success');
    Command('G1 X999 F60',1); Near(S.State.Position.X,0,'Bounds reject atomically');
    Command('G1 X10 F0',1); Near(S.State.Position.X,0,'Bad feed rejects');
    Command('G1 X F60',1); Check(Pos('Missing value',S.LastError)>0,'Missing axis value');
    Command('G20'); Command('G1 X1 F60',1); Near(S.State.Position.X,25.4,'Inch conversion');
    NewSession; Command('M302 P1'); Command('G1 X60 E6 F60',0);
    for I := 1 to 600 do S.Advance(0.1);
    Near(S.State.Position.X,60,'Small timestep endpoint'); Near(O.Deposit,6,'Small timestep material');
    Check(S.IsIdle,'Small timestep completion');
    Writeln('PASS sequencing, retry, emergency, bounded queue/input, unsupported commands');

    Check(Pair.BuildCreateArguments('com41','COM42',Args,Err),'Pair args');
    Check((Args.Count=3) and (Args[1]='PortName=COM41'),'Structured process args');
    Check(not Pair.BuildCreateArguments('COM1','com1',Args,Err),'Same port');
    Check(not Pair.BuildCreateArguments('COM1 & calc','COM2',Args,Err),'Reject injection');
    Check(not Pair.ValidPortName('COM01'),'Canonical port');
    Check(not Pair.CreatePair('COM41','COM42'),'Missing driver explicit failure');
    Writeln('PASS virtual serial validation; no driver installed or invoked');
    Writeln('ALL MARLIN COMPONENT TESTS PASSED');
  finally Args.Free; Pair.Free; O.Free; S.Free; end;
end.
