# -*- coding: utf-8 -*-
import os

langs = {
    'pt': {
        'title': 'Documentação da Aba AI Project',
        'intro': 'Esta pasta contém a paleta de componentes do Lazarus sob a aba **AI Project**.',
        'details': 'Referência Detalhada dos Componentes',
        'comp': 'Componente',
        'desc': 'Descrição',
        'props': 'Propriedades Importantes',
        'methods': 'Métodos Principais',
        'role': 'Papel do Agente de IA',
        'example': 'Exemplo de Código Lazarus',
        'dir': 'Diretório',
        'unified': 'Ponte de IA e Planejamento'
    },
    'en': {
        'title': 'Documentation for AI Project Tab',
        'intro': 'This folder contains the Lazarus components suite under the **AI Project** tab.',
        'details': 'Detailed Component Reference',
        'comp': 'Component',
        'desc': 'Description',
        'props': 'Important Properties',
        'methods': 'Main Methods',
        'role': 'AI Agent Role',
        'example': 'Lazarus Code Example',
        'dir': 'Directory',
        'unified': 'AI and Planning Bridge'
    },
    'es': {
        'title': 'Documentación de la Pestaña AI Project',
        'intro': 'Esta carpeta contiene la suite de componentes de Lazarus bajo la pestaña **AI Project**.',
        'details': 'Referencia Detallada de Componentes',
        'comp': 'Componente',
        'desc': 'Descripción',
        'props': 'Propiedades Importantes',
        'methods': 'Métodos Principales',
        'role': 'Rol del Agente de IA',
        'example': 'Ejemplo de Código Lazarus',
        'dir': 'Directorio',
        'unified': 'Puente de IA y Planificación'
    },
    'fr': {
        'title': 'Documentation de l\'onglet AI Project',
        'intro': 'Ce dossier contient la suite de composants Lazarus sous l\'onglet **AI Project**.',
        'details': 'Référence Détaillée des Composants',
        'comp': 'Composant',
        'desc': 'Description',
        'props': 'Propriétés Importantes',
        'methods': 'Méthodes Principales',
        'role': 'Rôle de l\'Agent d\'IA',
        'example': 'Exemple de Code Lazarus',
        'dir': 'Dossier',
        'unified': 'Pont d\'IA et de Planification'
    },
    'it': {
        'title': 'Documentazione della Scheda AI Project',
        'intro': 'Questa cartella contiene la suite di componenti Lazarus sotto la scheda **AI Project**.',
        'details': 'Riferimento Dettagliato dei Componenti',
        'comp': 'Componente',
        'desc': 'Descrizione',
        'props': 'Proprietà Importanti',
        'methods': 'Metodi Principali',
        'role': 'Ruolo dell\'Agente di IA',
        'example': 'Esempio di Codice Lazarus',
        'dir': 'Directory',
        'unified': 'Ponte di IA e Pianificazione'
    },
    'ar': {
        'title': 'توثيق علامة التبويب AI Project',
        'intro': 'يحتوي هذا المجموعة مكونات لازاروس ضمن علامة التبويب **AI Project**.',
        'details': 'مرجع المكونات التفصيلي',
        'comp': 'المكون',
        'desc': 'الوصف',
        'props': 'الخصائص الهامة',
        'methods': 'الأساليب الرئيسية',
        'role': 'دور وكيل الذكاء الاصطناعي',
        'example': 'مثال على كود لازاروس',
        'dir': 'المجلد',
        'unified': 'جسر الذكاء الاصطناعي والتخطيط'
    }
}

# The 20 components details in English and Portuguese
components_pt = [
    {'name': 'TAIProject', 'desc': 'Coordenador e cérebro global do projeto de IA.', 'props': 'ProjectName, Description, ChatGPT, Agent, Pipeline, DefaultProvider, DefaultModel, Token, LocalURL, SafeMode, SimulationMode', 'methods': 'Initialize, TestConnection, ExecuteText, Execute, LoadFromFile, SaveToFile', 'role': 'Centralizar chaves de segurança, carregar configurações de arquivos JSON e disparar execuções.'},
    {'name': 'TAIProjectLLMConfig', 'desc': 'Gerencia a configuração do provedor e modelo de LLM do projeto.', 'props': 'Project, Provider, Model, Endpoint, Token, SaveToken, Temperature, MaxTokens', 'methods': 'ApplyToProject, LoadFromProject, LoadFromChatGPT, ValidateConfig, TestConnection', 'role': 'Facilitar a parametrização do provedor de inteligência artificial (OpenAI, local/Ollama, etc.).'},
    {'name': 'TAIProjectStorage', 'desc': 'Gerencia a persistência e armazenamento local de dados do projeto.', 'props': 'Project, StoragePath, AutoSave, BackupOnSave', 'methods': 'SaveProject, LoadProject, CreateBackup, DeleteProject', 'role': 'Gravar e ler o estado completo do planejamento e tarefas do projeto no disco em formato JSON.'},
    {'name': 'TAIProjectDescription', 'desc': 'Armazena as informações descritivas básicas do escopo do projeto.', 'props': 'Project, ProjectName, Goal, Context, Scope, Constraints, ExpectedDeliverables', 'methods': 'LoadFromProject, SaveToProject, Clear', 'role': 'Guardar os parâmetros iniciais inseridos pelo usuário para a geração do plano.'},
    {'name': 'TAIAgileDocuments', 'desc': 'Gerencia artefatos de documentação ágil como Especificações e Histórias de Usuário.', 'props': 'Project, AutoGenerateDoc', 'methods': 'GenerateMarkdownSpecification, ExportToPDF, SaveDocToFile', 'role': 'Criar e exportar relatórios formatados em Markdown/PDF das especificações ágeis do projeto.'},
    {'name': 'TAIProjectTasks', 'desc': 'Gerencia a lista de tarefas e atividades geradas para o projeto.', 'props': 'Project, TasksCount', 'methods': 'AddTask, RemoveTask, GetTaskByID, UpdateTaskStatus, ClearTasks', 'role': 'Armazenar a lista de tarefas gerada pela IA, permitindo atualizar progresso e estados.'},
    {'name': 'TAIProjectSpecification', 'desc': 'Gera a especificação ágil estruturada usando LLM.', 'props': 'Project, PromptTemplate', 'methods': 'GenerateSpecification, GetSpecificationMarkdown', 'role': 'Elaborar o escopo detalhado de requisitos, épicos e critérios de aceite via IA.'},
    {'name': 'TAIProjectDependencies', 'desc': 'Analisa e mapeia dependências entre as tarefas do projeto.', 'props': 'Project', 'methods': 'AnalyzeDependencies, FindCircularDependencies, TopoSortTasks', 'role': 'Garantir que a ordem de execução das tarefas seja lógica e sequencial livre de loops.'},
    {'name': 'TAIProjectAgents', 'desc': 'Gerencia a lista de perfis de agentes alocados para o projeto.', 'props': 'Project, AgentsCount', 'methods': 'AddAgent, RemoveAgent, GetAgentByID, AssignTask', 'role': 'Alocar as personas de agentes de IA corretas para as tarefas apropriadas.'},
    {'name': 'TAITaskActions', 'desc': 'Executa ações no ciclo de vida de uma tarefa.', 'props': 'Project', 'methods': 'ExecuteAction, StartTask, FinishTask, BlockTask, RejectTask', 'role': 'Controlar as mudanças de estado (Iniciar, Pausar, Finalizar) das tarefas do projeto.'},
    {'name': 'TAIProjectReports', 'desc': 'Componente gerador de relatórios de progresso do projeto.', 'props': 'Project, ReportFormat', 'methods': 'GenerateProgressReport, GenerateGanttData, ExportReport', 'role': 'Compilar métricas e status de conclusão para visualização de relatórios gerenciais.'},
    {'name': 'TAIProjectRevisions', 'desc': 'Controla o histórico de revisões e alterações no planejamento.', 'props': 'Project, RevisionCount', 'methods': 'AddRevision, RestoreRevision, GetRevisionDetails', 'role': 'Rastrear o histórico de modificações sugeridas pelo usuário e respostas da IA.'},
    {'name': 'TAIProjectTaskGrid', 'desc': 'Controle visual para exibição e edição de tarefas em tabela.', 'props': 'Project, TaskGridColor', 'methods': 'RefreshGrid, LoadFromProject', 'role': 'Apresentar a grade de tarefas interativa na interface do Lazarus.'},
    {'name': 'TAIProjectGantt', 'desc': 'Controle gráfico para exibição de cronograma Gantt.', 'props': 'Project, HeaderColor, TaskBarColor', 'methods': 'DrawGantt, ExportToImage', 'role': 'Desenhar as barras de cronograma visualizando datas de início e fim das tarefas.'},
    {'name': 'TAIProjectTimeline', 'desc': 'Controle de linha do tempo com marcos e milestones.', 'props': 'Project, AxisColor, NodeColor', 'methods': 'DrawTimeline, AddEvent', 'role': 'Apresentar marcos históricos e ações executadas cronologicamente.'},
    {'name': 'TAIRiskMatrix', 'desc': 'Controle visual de matriz de riscos (probabilidade x impacto).', 'props': 'Project, CellSize', 'methods': 'DrawMatrix, LoadRisksFromProject', 'role': 'Renderizar o gráfico quadrático de riscos do projeto.'},
    {'name': 'TAIProjectStatusPanel', 'desc': 'Painel visual de progresso e KPIs rápidos.', 'props': 'Project, ShowGauges', 'methods': 'UpdatePanel', 'role': 'Mostrar gauges de conclusão e quantidade de tarefas concluídas.'},
    {'name': 'TAIAgentManagerFrame', 'desc': 'Frame de controle visual para gerenciar agentes de IA.', 'props': 'Project', 'methods': 'LoadAgents, SaveAgents', 'role': 'Disponibilizar interface pronta para cadastrar e editar agentes.'},
    {'name': 'TAITaskActionPanel', 'desc': 'Painel visual para acionar comandos sobre tarefas.', 'props': 'Project, ActiveTaskID', 'methods': 'LoadTask, ExecuteAction', 'role': 'Renderizar botões interativos para avançar o estado das tarefas.'},
    {'name': 'TAIProjectReportViewer', 'desc': 'Visualizador integrado de relatórios.', 'props': 'Project, ReportHTML', 'methods': 'LoadReport, PrintReport', 'role': 'Renderizar relatórios e planos de projeto na tela em formato rico.'}
]

components_en = [
    {'name': 'TAIProject', 'desc': 'Global AI project coordinator and manager.', 'props': 'ProjectName, Description, ChatGPT, Agent, Pipeline, DefaultProvider, DefaultModel, Token, LocalURL, SafeMode, SimulationMode', 'methods': 'Initialize, TestConnection, ExecuteText, Execute, LoadFromFile, SaveToFile', 'role': 'Centralize security keys, load JSON project setups, and execute routines.'},
    {'name': 'TAIProjectLLMConfig', 'desc': 'Manages the LLM provider and model configuration of the project.', 'props': 'Project, Provider, Model, Endpoint, Token, SaveToken, Temperature, MaxTokens', 'methods': 'ApplyToProject, LoadFromProject, LoadFromChatGPT, ValidateConfig, TestConnection', 'role': 'Ease the configuration of the AI provider (OpenAI, local/Ollama, etc.).'},
    {'name': 'TAIProjectStorage', 'desc': 'Manages persistence and local storage of project data.', 'props': 'Project, StoragePath, AutoSave, BackupOnSave', 'methods': 'SaveProject, LoadProject, CreateBackup, DeleteProject', 'role': 'Write and read the complete state of project planning and tasks on disk in JSON.'},
    {'name': 'TAIProjectDescription', 'desc': 'Stores the basic descriptive scope information of the project.', 'props': 'Project, ProjectName, Goal, Context, Scope, Constraints, ExpectedDeliverables', 'methods': 'LoadFromProject, SaveToProject, Clear', 'role': 'Retain the initial parameters inputted by the user for plan generation.'},
    {'name': 'TAIAgileDocuments', 'desc': 'Manages agile documentation artifacts like Specifications and User Stories.', 'props': 'Project, AutoGenerateDoc', 'methods': 'GenerateMarkdownSpecification, ExportToPDF, SaveDocToFile', 'role': 'Create and export formatted Markdown/PDF reports of agile project specifications.'},
    {'name': 'TAIProjectTasks', 'desc': 'Manages the list of tasks and activities generated for the project.', 'props': 'Project, TasksCount', 'methods': 'AddTask, RemoveTask, GetTaskByID, UpdateTaskStatus, ClearTasks', 'role': 'Store the task list generated by AI, allowing status and progress updates.'},
    {'name': 'TAIProjectSpecification', 'desc': 'Generates structured agile specification using LLM.', 'props': 'Project, PromptTemplate', 'methods': 'GenerateSpecification, GetSpecificationMarkdown', 'role': 'Elaborate detailed scope of requirements, epics, and acceptance criteria via AI.'},
    {'name': 'TAIProjectDependencies', 'desc': 'Analyzes and maps dependencies between project tasks.', 'props': 'Project', 'methods': 'AnalyzeDependencies, FindCircularDependencies, TopoSortTasks', 'role': 'Ensure that the task execution sequence is logical and loop-free.'},
    {'name': 'TAIProjectAgents', 'desc': 'Manages the list of agent profiles allocated to the project.', 'props': 'Project, AgentsCount', 'methods': 'AddAgent, RemoveAgent, GetAgentByID, AssignTask', 'role': 'Allocate the correct AI agent personas to the appropriate tasks.'},
    {'name': 'TAITaskActions', 'desc': 'Executes actions in a task\'s lifecycle.', 'props': 'Project', 'methods': 'ExecuteAction, StartTask, FinishTask, BlockTask, RejectTask', 'role': 'Control state transitions (Start, Pause, Finish) of project tasks.'},
    {'name': 'TAIProjectReports', 'desc': 'Report generator component for project progress.', 'props': 'Project, ReportFormat', 'methods': 'GenerateProgressReport, GenerateGanttData, ExportReport', 'role': 'Compile metrics and completion status for management reports.'},
    {'name': 'TAIProjectRevisions', 'desc': 'Controls the revision history and planning adjustments.', 'props': 'Project, RevisionCount', 'methods': 'AddRevision, RestoreRevision, GetRevisionDetails', 'role': 'Track the modification history suggested by the user and AI replies.'},
    {'name': 'TAIProjectTaskGrid', 'desc': 'Visual grid control for displaying and editing tasks.', 'props': 'Project, TaskGridColor', 'methods': 'RefreshGrid, LoadFromProject', 'role': 'Present the interactive task grid in the Lazarus interface.'},
    {'name': 'TAIProjectGantt', 'desc': 'Graphical control for rendering Gantt schedules.', 'props': 'Project, HeaderColor, TaskBarColor', 'methods': 'DrawGantt, ExportToImage', 'role': 'Draw schedule bars visualizing task start and end dates.'},
    {'name': 'TAIProjectTimeline', 'desc': 'Timeline control with milestones and events.', 'props': 'Project, AxisColor, NodeColor', 'methods': 'DrawTimeline, AddEvent', 'role': 'Present chronological milestones and executed actions.'},
    {'name': 'TAIRiskMatrix', 'desc': 'Visual risk matrix control (likelihood vs impact).', 'props': 'Project, CellSize', 'methods': 'DrawMatrix, LoadRisksFromProject', 'role': 'Render the quadratic project risk matrix.'},
    {'name': 'TAIProjectStatusPanel', 'desc': 'Visual panel for progress and quick KPIs.', 'props': 'Project, ShowGauges', 'methods': 'UpdatePanel', 'role': 'Show completion gauges and completed task counts.'},
    {'name': 'TAIAgentManagerFrame', 'desc': 'Visual control frame to manage AI agents.', 'props': 'Project', 'methods': 'LoadAgents, SaveAgents', 'role': 'Provide ready-made UI to register and edit agents.'},
    {'name': 'TAITaskActionPanel', 'desc': 'Visual panel to trigger commands on tasks.', 'props': 'Project, ActiveTaskID', 'methods': 'LoadTask, ExecuteAction', 'role': 'Render interactive buttons to advance task states.'},
    {'name': 'TAIProjectReportViewer', 'desc': 'Integrated report viewer.', 'props': 'Project, ReportHTML', 'methods': 'LoadReport, PrintReport', 'role': 'Render reports and project plans on screen in rich formatting.'}
]

data = {
    'icon': '[IA]',
    'pt': {
        'desc': 'Coordenação Avançada de Projetos de IA e Pipelines de Execução.',
        'info': 'Centraliza e automatiza a conexão entre os diversos módulos do projeto.',
        'comps': components_pt
    },
    'en': {
        'desc': 'Advanced AI Project Coordination and Execution Pipelines.',
        'info': 'Centralizes and automates the flow between various modules.',
        'comps': components_en
    },
    'es': {
        'desc': 'Coordinación Avanzada de Proyectos de IA y Pipelines de Ejecución.',
        'info': 'Centraliza y automatiza la conexión entre los diversos módulos.',
        'comps': components_en # English as fallback
    },
    'fr': {
        'desc': 'Coordination Avancée de Projets d\'IA et Pipelines de Traitement.',
        'info': 'Centralise et automatise les flux d\'exécution entre les modules.',
        'comps': components_en # English as fallback
    },
    'it': {
        'desc': 'Coordinamento Avanzato di Progetti IA e Pipeline di Esecuzione.',
        'info': 'Centralizza e automatizza il flusso di lavoro tra i vari moduli.',
        'comps': components_en # English as fallback
    },
    'ar': {
        'desc': 'التنسيق المتقدم لمشاريع الذكاء الاصطناعي وخطوط الأنابيب البرمجية.',
        'info': 'يركز ويؤتمت الاتصال بين وحدات المشروع المختلفة.',
        'comps': components_en # English as fallback
    }
}

lazarus_example = """
```pascal
var
  MyProject: TAIProject;
  MySpecification: TAIProjectSpecification;
begin
  MyProject := TAIProject.Create(Self);
  MySpecification := TAIProjectSpecification.Create(Self);
  try
    MyProject.ProjectName := 'Smart Factory AI';
    MyProject.ChatGPT := ChatGPT1;
    
    MySpecification.Project := MyProject;
    
    if MyProject.Execute then
      ShowMessage('Sucesso')
    else
      ShowMessage(MyProject.LastError);
  finally
    MySpecification.Free;
    MyProject.Free;
  end;
end;
```
"""

def generate():
    package_root = os.path.dirname(os.path.abspath(__file__))
    folder_path = os.path.join(package_root, "AI Project")
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
        
    for lang_code, lang_trans in langs.items():
        lang_data = data[lang_code]
        filename = f"README.{lang_code}.md"
        filepath = os.path.join(folder_path, filename)
        
        # Build markdown content
        content = []
        content.append(f"# {data['icon']} {lang_trans['title']}")
        content.append("")
        content.append(f"> [!NOTE]")
        content.append(f"> {lang_trans['intro']}")
        content.append("")
        content.append(f"## {lang_data['desc']}")
        content.append(f"{lang_data['info']}")
        content.append("")
        content.append(f"### {lang_trans['details']}")
        content.append("")
        
        # Components table
        content.append(f"| {lang_trans['comp']} | {lang_trans['desc']} | {lang_trans['props']} | {lang_trans['methods']} | {lang_trans['role']} |")
        content.append("|---|---|---|---|---|")
        for c in lang_data['comps']:
            content.append(f"| **{c['name']}** | {c['desc']} | `{c['props']}` | `{c['methods']}` | {c['role']} |")
        content.append("")
        
        # Lazarus Code Example
        first_classname = lang_data['comps'][0]['name']
        content.append(f"### [Code] {lang_trans['example']} ({first_classname})")
        ex_code = lazarus_example.replace("{classname}", first_classname)
        content.append(ex_code)
        content.append("")
        
        # Unified Bridge mention
        content.append(f"### [Bridge] {lang_trans['unified']}")
        if lang_code == 'pt':
            content.append("Cada um destes componentes possui uma propriedade published `Prompt` que documenta sua API de forma transparente para orientar Agentes de IA (`TAIAgent`) de forma automática!")
        elif lang_code == 'en':
            content.append("Each of these components features a published `Prompt` property that transparently documents its API to guide AI Agents (`TAIAgent`) autonomously!")
        elif lang_code == 'es':
            content.append("Cada uno de estos componentes cuenta con una propiedad published `Prompt` que documenta de forma transparente su API para guiar a Agentes de IA (`TAIAgent`) de manera autónoma.")
        elif lang_code == 'fr':
            content.append("Chacun de ces composants intègre une propriété published `Prompt` documentant de manière transparente son API pour guider les agents d'IA (`TAIAgent`) de façon autonome.")
        elif lang_code == 'it':
            content.append("Ciascuno di questi componentes include una proprietà published `Prompt` que documenta in modo trasparente le proprie API per orientare gli Agenti IA (`TAIAgent`) autonomamente.")
        elif lang_code == 'ar':
            content.append("تميز كل مكون من هذه المكونات بخاصية نشر `Prompt` والتي توثق بشكل شفاف وتوثيق واجهتها البرمجية لتوجيه وكلاء الذكاء الاصطناعي (`TAIAgent`) ذاتياً!")
            
        content.append("")
        
        # Save file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("\n".join(content))
            
        print(f"Generated: {filepath}")

    # Also generate the main landing README.md for the folder
    readme_path = os.path.join(folder_path, "README.md")
    readme_content = """# [IA] Lazarus AI Suite - Tab: `AI Project`

> [!NOTE]
> Advanced AI Project Coordination and Execution Pipelines.

Please select your preferred language for the component reference manual:

---

## [Globe] Select Language / Selecione o Idioma

| Language | Country Flag | Documentation Link |
|---|---|---|
| **Português (PT)** | BR / PT | [README.pt.md](README.pt.md) |
| **English (EN)** | US / GB | [README.en.md](README.en.md) |
| **Español (ES)** | ES / MX | [README.es.md](README.es.md) |
| **Français (FR)** | FR | [README.fr.md](README.fr.md) |
| **Italiano (IT)** | IT | [README.it.md](README.it.md) |
| **العربية (AR)** | AE / SA | [README.ar.md](README.ar.md) |

---

### [Bridge] AI and Hardware Integration
Each component in this folder features a published `Prompt` property that documents its API structure to automatically guide AI Agents (`TAIAgent`) in runtime.
"""
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)
    print(f"Generated Landing Index: {readme_path}")

if __name__ == '__main__':
    generate()
